import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-screen overflow-hidden bg-[url('/wallpaper.webp')] bg-cover bg-center bg-no-repeat">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
