import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Provides the application's root HTML structure including <html lang="en">, a body with the site background and the Navbar, and renders page content.
 *
 * @param children - The content to render inside the body.
 * @returns The root JSX element containing the HTML and body structure for the app.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen w-screen overflow-hidden bg-[url('/wallpapers/wallpaper1.webp')] bg-cover bg-center bg-no-repeat">
        <Navbar />
        {children}
      </body>
    </html>
  );
}